### ISSUE TITLE
Error when trying to add app to my account

### ISSUE THREAD

**Issue by DanielStutzbach** [ahndee/Envoy-ST#2]
This is my first time trying to add a custom app to my SmartThings, so I'm probably doing something wrong.  Any help would be appreciated!

When I go to https://graph.api.smartthings.com/ide/app/saveFromCode and paste in the code from https://raw.githubusercontent.com/ahndee/Envoy-ST/master/devicetypes/aamann/enlighten-envoy-local.src/enlighten-envoy-local.groovy, I get the following error:

No signature of method: script14845225286271511565877.metadata() is applicable for argument types: (script14845225286271511565877$_run_closure2) values: [script14845225286271511565877$_run_closure2@2d154b1e] Possible solutions: getMetadata(), getState(), pullData(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

Any ideas?

**Comment by ahndee** [comment]
You are trying to paste the device handler code into the code for a new SmartApp - that won't work. You need to use the "From Code" tab on https://graph.api.smartthings.com/ide/device/create/ instead

**Comment by manideepa03** [comment]
Hello, I am trying to understand the smarthings smartapp code written by someone. I see that the https://graph.api.smartthings.com/ide/app/saveFromCode gives 405 error. Can you please let me know how do I fix this error?

**Comment by ahndee** [comment]
Same answer are the one just above your question – you are trying to add a device type handler as a smart app…

**Comment by manideepa03** [comment]
Thank you for the reply.  The code tries to send a POST request to add a smartapp considering https://graph.api.smartthings.com/ide/app/saveFromCode as the base URL. I'm assuming that the smarthings UI has been changed. Can you please let me know what are the contents in that URL so I can get the idea about it.

**Comment by gmsemaan** [comment]
Hello, sorry i am kinda opening an old issue perhaps but i was able to copy the code for the handler, but where is the code for the smartapp? I am most likely missing something really obvious here so excuse me in advance... but i looked and searched as much as i could for hours... and i got nothing and i am pretty sure it is really simple. any help is appreciated. 
Thank you

**Comment by ahndee** [comment]
There is no SmartApp. The DTH is all that is needed.

**Comment by gmsemaan** [comment]
Thank you for your response!!! i greatly appreciate it!

So this is not like what i am used to, adding a handler and then a smart
app. i added the handler so how to do i view the data in smartthings
without a smartapp? is there a procedure written down somewhere i can
follow?

THANK YOU!
